/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fenbi.truman;

public class EngineConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trumanJNI.delete_EngineConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVideo_port(int value) {
    trumanJNI.EngineConfig_video_port_set(swigCPtr, this, value);
  }

  public int getVideo_port() {
    return trumanJNI.EngineConfig_video_port_get(swigCPtr, this);
  }

  public void setAudio_port(int value) {
    trumanJNI.EngineConfig_audio_port_set(swigCPtr, this, value);
  }

  public int getAudio_port() {
    return trumanJNI.EngineConfig_audio_port_get(swigCPtr, this);
  }

  public EngineConfig() {
    this(trumanJNI.new_EngineConfig(), true);
  }

}
