/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fenbi.truman;

public class Engine {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Engine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Engine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trumanJNI.delete_Engine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int InitEngine(EngineConfig config) {
    return trumanJNI.Engine_InitEngine(swigCPtr, this, EngineConfig.getCPtr(config), config);
  }

  public void SetEngineCallback(EngineCallback callback) {
    trumanJNI.Engine_SetEngineCallback(swigCPtr, this, EngineCallback.getCPtr(callback), callback);
  }

  public int Run() {
    return trumanJNI.Engine_Run(swigCPtr, this);
  }

  public Engine() {
    this(trumanJNI.new_Engine(), true);
  }

}
